'use strict'

module.exports = {
  'rules': {
    'no-cond-assign': [2, 'always'],
    'no-console': 0,
    'no-constant-condition': 2,
    'no-control-regex': 2,
    'no-debugger': 2,
    'no-dupe-args': 2,
    'no-dupe-keys': 2,
    'no-duplicate-case': 2,
    'no-empty-character-class': 2,
    'no-empty': 2,
    'no-ex-assign': 2,
    'no-extra-boolean-cast': 2,
    'no-extra-parens': [2, 'functions'],
    'no-extra-semi': 2,
    'no-func-assign': 2,
    'no-inner-declarations': [2, 'functions'],
    'no-invalid-regexp': 2,
    'no-irregular-whitespace': 2,
    'no-obj-calls': 2,
    'no-prototype-builtins': 2,
    'no-regex-spaces': 2,
    'no-sparse-arrays': 2,
    'no-template-curly-in-string': 2,
    'no-unexpected-multiline': 2,
    'no-unreachable': 2,
    'no-unsafe-finally': 2,
    'no-unsafe-negation': 2,
    'use-isnan': 2,
    'valid-jsdoc': 0,
    'valid-typeof': 2,


    'accessor-pairs': 2,
    'array-callback-return': 2,
    'block-scoped-var': 2,
    'class-methods-use-this': 2,
    'complexity': [0, 11],
    'consistent-return': 2,
    'curly': [2, 'all'],
    'default-case': 2,
    'dot-location': [2, 'property'],
    'dot-notation': 2,
    'eqeqeq': [2, 'smart'],
    'guard-for-in': 2,
    'no-alert': 2,
    'no-caller': 2,
    'no-case-declarations': 2,
    'no-div-regex': 0,
    'no-else-return': 2,
    'no-empty-function': 2,
    'no-empty-pattern': 2,
    'no-eq-null': 2,
    'no-eval': 2,
    'no-extend-native': 2,
    'no-extra-bind': 2,
    'no-extra-label': 2,
    'no-fallthrough': 2,
    'no-floating-decimal': 2,
    'no-global-assign': [2, { 'exceptions': [] }],
    'no-implicit-coercion': [2, {
      'boolean': true,
      'number': true,
      'string': true,
      'allow': []
    }],
    'no-implicit-globals': 0,
    'no-implied-eval': 2,
    'no-invalid-this': 2,
    'no-iterator': 2,
    'no-labels': 2,
    'no-lone-blocks': 2,
    'no-loop-func': 2,
    'no-magic-numbers': 0,
    'no-multi-spaces': 2,
    'no-multi-str': 2,
    'no-new-func': 2,
    'no-new-wrappers': 2,
    'no-new': 2,
    'no-octal-escape': 2,
    'no-octal': 2,
    'no-param-reassign': [2, { 'props': false }],
    'no-proto': 2,
    'no-redeclare': 2,
    'no-restricted-properties': [0, {
      'object': 'disallowedObjectName',
      'property': 'anotherDisallowedPropertyName',
      'message': 'Please use allowedObjectName.allowedPropertyName.'
    }],
    'no-return-assign': [2, 'always'],
    'no-script-url': 2,
    'no-self-assign': 2,
    'no-self-compare': 2,
    'no-sequences': 2,
    'no-throw-literal': 2,
    'no-unmodified-loop-condition': 2,
    'no-unused-expressions': [2, { 'allowShortCircuit': false, 'allowTernary': false }],
    'no-unused-labels': 2,
    'no-useless-call': 2,
    'no-useless-concat': 2,
    'no-useless-escape': 2,
    'no-void': 2,
    'no-warning-comments': [1, { 'terms': ['todo', 'fixme', 'xxx'], 'location': 'start' }],
    'no-with': 2,
    'radix': [2, 'always'],
    'vars-on-top': 0,
    'wrap-iife': [2, 'inside'],
    'yoda': 0,


    'strict': [2, 'global'],


    'init-declarations': 0,
    'no-catch-shadow': 2,
    'no-delete-var': 2,
    'no-label-var': 2,
    'no-restricted-globals': [0, 'fdesctibe'],
    'no-shadow-restricted-names': 2,
    'no-shadow': 2,
    'no-undef-init': 2,
    'no-undef': [2, { 'typeof': false }],
    'no-undefined': 2,
    'no-unused-vars': [2, { 'vars': 'all', 'args': 'after-used' }],
    'no-use-before-define': [2, { 'functions': true, 'classes': true }],


    'callback-return': [2, ['callback', 'cb', 'next']],
    'global-require': 2,
    'handle-callback-err': [2, '^(err|error|anySpecificError)$'],
    'no-mixed-requires': [2, { 'grouping': true, 'allowCall': true }],
    'no-new-require': 2,
    'no-path-concat': 2,
    'no-process-env': 2,
    'no-process-exit': 2,
    'no-restricted-modules': [2],
    'no-sync': 0,


    'array-bracket-spacing': [2, 'never'],
    'block-spacing': [2, 'always'],
    'brace-style': [2, '1tbs'],
    'camelcase': 0,
    'comma-dangle': [2, 'never'],
    'comma-spacing': [2, { 'before': false, 'after': true }],
    'comma-style': [2, 'last'],
    'computed-property-spacing': [2, 'never'],
    'consistent-this': [2, 'self'],
    'eol-last': [2, 'unix'],
    'func-call-spacing': [2, 'never'],
    'func-names': 0,
    'func-style': [2, 'declaration', { 'allowArrowFunctions': true }],
    'id-blacklist': [0, 'data'],
    'id-length': [0, { 'min': 3, 'max': 10, 'properties': 'always', 'exceptions': [] }],
    'id-match': [2, '^\\$?[a-zA-Z_]*$', { 'properties': true }],
    'indent': [2, 2, { 'SwitchCase': 2, 'VariableDeclarator': 2 }],
    'jsx-quotes': 0,
    'key-spacing': [2, {
      'singleLine': {
        'beforeColon': false,
        'afterColon': true
      },
      'multiLine': {
        'beforeColon': false,
        'afterColon': true
      }
    }],
    'keyword-spacing': [2, { 'before': true, 'after': true, 'overrides': {} }],
    'line-comment-position': 0,
    'linebreak-style': [2, 'unix'],
    'lines-around-comment': 0,
    'lines-around-directive': [2, 'always'],
    'max-depth': [0, 3],
    'max-len': [0, { 'code': 80, 'tabWidth': 4, 'ignoreUrls': false }],
    'max-lines': [0, { 'max': 300, 'skipBlankLines': true }],
    'max-nested-callbacks': [0, 3],
    'max-params': [0, 7],
    'max-statements-per-line': [0, { 'max': 1 }],
    'max-statements': [0, 10, { 'ignoreTopLevelFunctions': false }],
    'multiline-ternary': [0, 'never'],
    'new-cap': [2, { 'capIsNewExceptions': [] }],
    'new-parens': 2,
    'newline-after-var': [0, 'always'],
    'newline-before-return': 0,
    'newline-per-chained-call': [0, { 'ignoreChainWithDepth': 3 }],
    'no-array-constructor': 2,
    'no-bitwise': 0,
    'no-continue': 2,
    'no-inline-comments': 0,
    'no-lonely-if': 2,
    'no-mixed-operators': [0, {
      'groups': [
          ['+', '-', '*', '/', '%', '**'],
          ['&', '|', '^', '~', '<<', '>>', '>>>'],
          ['==', '!=', '===', '!==', '>', '>=', '<', '<='],
          ['&&', '||'],
          ['in', 'instanceof']
      ],
      'allowSamePrecedence': true
    }],
    'no-mixed-spaces-and-tabs': 0,
    'no-multiple-empty-lines': [2, { 'max': 2, 'maxEOF': 1 }],
    'no-negated-condition': 0,
    'no-nested-ternary': 2,
    'no-new-object': 2,
    'no-plusplus': [2, { 'allowForLoopAfterthoughts': true }],
    'no-restricted-syntax': [2, 'SwitchStatement', 'BreakStatement'],
    'no-tabs': 2,
    'no-ternary': 0,
    'no-trailing-spaces': [2, { 'skipBlankLines': false }],
    'no-underscore-dangle': [2, { 'allow': [], 'allowAfterThis': false }],
    'no-unneeded-ternary': 2,
    'no-whitespace-before-property': 2,
    'object-curly-newline': [0, 'always'],
    'object-curly-spacing': [2, 'always'],
    'object-property-newline': [0, { 'allowMultiplePropertiesPerLine': false }],
    'one-var-declaration-per-line': [2, 'always'],
    'one-var': [2, 'never'],
    'operator-assignment': [2, 'always'],
    'operator-linebreak': [2, 'none'],
    'padded-blocks': [2, 'never'],
    'quote-props': [2, 'consistent'],
    'quotes': [2, 'single', 'avoid-escape'],
    'require-jsdoc': 0,
    'semi-spacing': [2, { 'before': false, 'after': true }],
    'semi': [2, 'never'],
    'sort-keys': [0, 'asc', { 'caseSensitive': true, 'natural': false }],
    'sort-vars': 0,
    'space-before-blocks': [2, { 'functions': 'always', 'keywords': 'always', 'classes': 'always' }],
    'space-before-function-paren': [2, 'never'],
    'space-in-parens': [2, 'never'],
    'space-infix-ops': [2, { 'int32Hint': true }],
    'space-unary-ops': [2, { 'words': true, 'nonwords': false }],
    'spaced-comment': [2, 'always', {
      'line': { 'exceptions': ['/', '-'] },
      'block': { 'exceptions': ['*'] }
    }],
    'unicode-bom': [2, 'never'],
    'wrap-regex': 0,


    'arrow-body-style': [2, 'as-needed'],
    'arrow-parens': [2, 'as-needed'],
    'arrow-spacing': [2, { 'before': true, 'after': true }],
    'constructor-super': 2,
    'generator-star-spacing': [2, { 'before': true, 'after': true }],
    'no-class-assign': 2,
    'no-confusing-arrow': 0,
    'no-const-assign': 2,
    'no-dupe-class-members': 2,
    'no-duplicate-imports': [2, { 'includeExports': true }],
    'no-new-symbol': 2,
    'no-restricted-imports': [2],
    'no-this-before-super': 2,
    'no-useless-computed-key': 2,
    'no-useless-constructor': 2,
    'no-useless-rename': [2, {
      'ignoreDestructuring': false,
      'ignoreImport': false,
      'ignoreExport': false
    }],
    'no-var': 2,
    'object-shorthand': [2, 'always'],
    'prefer-arrow-callback': 2,
    'prefer-const': 2,
    'prefer-numeric-literals': 2,
    'prefer-reflect': [0, { 'exceptions': [] }],
    'prefer-rest-params': 0,
    'prefer-spread': 0,
    'prefer-template': 2,
    'require-yield': 2,
    'rest-spread-spacing': [2, 'never'],
    'sort-imports': 0,
    'symbol-description': 2,
    'template-curly-spacing': [2, 'never'],
    'yield-star-spacing': [2, { 'before': true, 'after': true }]
  }
}
